<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Patient;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $patients = [
            [
                'medical_record_number' => 'RM-202601-0001',
                'nik' => '3201010101010001',
                'bpjs_number' => '0001234567890',
                'name' => 'Budi Santoso',
                'birth_place' => 'Jakarta',
                'birth_date' => '1985-05-15',
                'gender' => 'male',
                'blood_type' => 'A',
                'religion' => 'islam',
                'marital_status' => 'married',
                'occupation' => 'Karyawan Swasta',
                'education' => 'S1',
                'phone' => '081234567890',
                'email' => 'budi.santoso@email.com',
                'address' => 'Jl. Merdeka No. 123',
                'rt' => '001',
                'rw' => '002',
                'village' => 'Menteng',
                'district' => 'Menteng',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10310',
                'emergency_contact_name' => 'Siti Santoso',
                'emergency_contact_relation' => 'Istri',
                'emergency_contact_phone' => '081234567891',
                'allergies' => 'Penisilin',
                'patient_type' => 'bpjs',
                'is_active' => true,
            ],
            [
                'medical_record_number' => 'RM-202601-0002',
                'nik' => '3201020202020002',
                'name' => 'Siti Rahayu',
                'birth_place' => 'Bandung',
                'birth_date' => '1990-08-22',
                'gender' => 'female',
                'blood_type' => 'B',
                'religion' => 'islam',
                'marital_status' => 'single',
                'occupation' => 'Guru',
                'education' => 'S1',
                'phone' => '082345678901',
                'email' => 'siti.rahayu@email.com',
                'address' => 'Jl. Sudirman No. 45',
                'rt' => '003',
                'rw' => '005',
                'village' => 'Setiabudi',
                'district' => 'Setiabudi',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'postal_code' => '12910',
                'emergency_contact_name' => 'Ahmad Rahayu',
                'emergency_contact_relation' => 'Ayah',
                'emergency_contact_phone' => '082345678902',
                'patient_type' => 'umum',
                'is_active' => true,
            ],
            [
                'medical_record_number' => 'RM-202601-0003',
                'nik' => '3201030303030003',
                'bpjs_number' => '0001234567891',
                'name' => 'Ahmad Hidayat',
                'birth_place' => 'Surabaya',
                'birth_date' => '1978-12-01',
                'gender' => 'male',
                'blood_type' => 'O',
                'religion' => 'islam',
                'marital_status' => 'married',
                'occupation' => 'Wiraswasta',
                'education' => 'SMA',
                'phone' => '083456789012',
                'address' => 'Jl. Gatot Subroto No. 78',
                'rt' => '004',
                'rw' => '007',
                'village' => 'Kuningan',
                'district' => 'Setiabudi',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'postal_code' => '12940',
                'emergency_contact_name' => 'Fatimah Hidayat',
                'emergency_contact_relation' => 'Istri',
                'emergency_contact_phone' => '083456789013',
                'allergies' => 'Seafood',
                'medical_notes' => 'Riwayat hipertensi',
                'patient_type' => 'bpjs',
                'is_active' => true,
            ],
            [
                'medical_record_number' => 'RM-202601-0004',
                'nik' => '3201040404040004',
                'name' => 'Dewi Lestari',
                'birth_place' => 'Yogyakarta',
                'birth_date' => '1995-03-10',
                'gender' => 'female',
                'blood_type' => 'AB',
                'religion' => 'katolik',
                'marital_status' => 'married',
                'occupation' => 'Akuntan',
                'education' => 'S1',
                'phone' => '084567890123',
                'email' => 'dewi.lestari@email.com',
                'address' => 'Jl. Thamrin No. 56',
                'rt' => '002',
                'rw' => '004',
                'village' => 'Gondangdia',
                'district' => 'Menteng',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10350',
                'emergency_contact_name' => 'Rudi Lestari',
                'emergency_contact_relation' => 'Suami',
                'emergency_contact_phone' => '084567890124',
                'patient_type' => 'asuransi',
                'insurance_name' => 'Prudential',
                'insurance_number' => 'PRU-2024-00123',
                'is_active' => true,
            ],
            [
                'medical_record_number' => 'RM-202601-0005',
                'nik' => '3201050505050005',
                'name' => 'Rudi Hartono',
                'birth_place' => 'Semarang',
                'birth_date' => '1982-07-25',
                'gender' => 'male',
                'blood_type' => 'B',
                'religion' => 'kristen',
                'marital_status' => 'divorced',
                'occupation' => 'Dokter',
                'education' => 'S2',
                'phone' => '085678901234',
                'email' => 'rudi.hartono@email.com',
                'address' => 'Jl. Rasuna Said No. 89',
                'rt' => '006',
                'rw' => '008',
                'village' => 'Karet Kuningan',
                'district' => 'Setiabudi',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'postal_code' => '12950',
                'emergency_contact_name' => 'Linda Hartono',
                'emergency_contact_relation' => 'Ibu',
                'emergency_contact_phone' => '085678901235',
                'medical_notes' => 'Diabetes tipe 2',
                'patient_type' => 'umum',
                'is_active' => true,
            ],
            [
                'medical_record_number' => 'RM-202601-0006',
                'nik' => '3201060606060006',
                'bpjs_number' => '0001234567892',
                'name' => 'Ani Wijaya',
                'birth_place' => 'Medan',
                'birth_date' => '2015-11-30',
                'gender' => 'female',
                'blood_type' => 'A',
                'religion' => 'buddha',
                'phone' => '086789012345',
                'address' => 'Jl. Kebon Sirih No. 12',
                'rt' => '001',
                'rw' => '003',
                'village' => 'Kebon Sirih',
                'district' => 'Menteng',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10340',
                'emergency_contact_name' => 'Hendra Wijaya',
                'emergency_contact_relation' => 'Ayah',
                'emergency_contact_phone' => '086789012346',
                'allergies' => 'Kacang',
                'patient_type' => 'bpjs',
                'is_active' => true,
            ],
            [
                'medical_record_number' => 'RM-202601-0007',
                'nik' => '3201070707070007',
                'name' => 'Joko Susanto',
                'birth_place' => 'Solo',
                'birth_date' => '1970-02-14',
                'gender' => 'male',
                'blood_type' => 'O',
                'religion' => 'islam',
                'marital_status' => 'widowed',
                'occupation' => 'Pensiunan',
                'education' => 'SMA',
                'phone' => '087890123456',
                'address' => 'Jl. Cikini Raya No. 34',
                'rt' => '005',
                'rw' => '009',
                'village' => 'Cikini',
                'district' => 'Menteng',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10330',
                'emergency_contact_name' => 'Bambang Susanto',
                'emergency_contact_relation' => 'Anak',
                'emergency_contact_phone' => '087890123457',
                'medical_notes' => 'Riwayat stroke ringan, kolesterol tinggi',
                'patient_type' => 'umum',
                'is_active' => true,
            ],
            [
                'medical_record_number' => 'RM-202601-0008',
                'nik' => '3201080808080008',
                'name' => 'Maria Christina',
                'birth_place' => 'Manado',
                'birth_date' => '1988-09-05',
                'gender' => 'female',
                'blood_type' => 'AB',
                'religion' => 'katolik',
                'marital_status' => 'married',
                'occupation' => 'Pengusaha',
                'education' => 'S2',
                'phone' => '088901234567',
                'email' => 'maria.christina@email.com',
                'address' => 'Jl. Senopati No. 67',
                'rt' => '003',
                'rw' => '006',
                'village' => 'Senayan',
                'district' => 'Kebayoran Baru',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'postal_code' => '12190',
                'emergency_contact_name' => 'John Christina',
                'emergency_contact_relation' => 'Suami',
                'emergency_contact_phone' => '088901234568',
                'patient_type' => 'asuransi',
                'insurance_name' => 'Allianz',
                'insurance_number' => 'ALZ-2024-00456',
                'is_active' => true,
            ],
            [
                'medical_record_number' => 'RM-202601-0009',
                'nik' => '3201090909090009',
                'bpjs_number' => '0001234567893',
                'name' => 'Eko Prasetyo',
                'birth_place' => 'Malang',
                'birth_date' => '1992-06-18',
                'gender' => 'male',
                'blood_type' => 'A',
                'religion' => 'islam',
                'marital_status' => 'married',
                'occupation' => 'Programmer',
                'education' => 'S1',
                'phone' => '089012345678',
                'email' => 'eko.prasetyo@email.com',
                'address' => 'Jl. Kuningan No. 23',
                'rt' => '007',
                'rw' => '010',
                'village' => 'Kuningan Timur',
                'district' => 'Setiabudi',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'postal_code' => '12950',
                'emergency_contact_name' => 'Nina Prasetyo',
                'emergency_contact_relation' => 'Istri',
                'emergency_contact_phone' => '089012345679',
                'patient_type' => 'bpjs',
                'is_active' => true,
            ],
            [
                'medical_record_number' => 'RM-202601-0010',
                'nik' => '3201101010101010',
                'name' => 'Ratna Sari',
                'birth_place' => 'Denpasar',
                'birth_date' => '2000-12-25',
                'gender' => 'female',
                'blood_type' => 'B',
                'religion' => 'hindu',
                'marital_status' => 'single',
                'occupation' => 'Mahasiswa',
                'education' => 'SMA',
                'phone' => '081123456789',
                'email' => 'ratna.sari@email.com',
                'address' => 'Jl. Salemba No. 45',
                'rt' => '002',
                'rw' => '004',
                'village' => 'Kenari',
                'district' => 'Senen',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10430',
                'emergency_contact_name' => 'Wayan Sari',
                'emergency_contact_relation' => 'Ibu',
                'emergency_contact_phone' => '081123456790',
                'patient_type' => 'umum',
                'is_active' => true,
            ],
        ];

        foreach ($patients as $patient) {
            Patient::create($patient);
        }
    }
}
